apiVersion: v1
kind: Service
metadata:
  name: operative-report-web-service
  labels:
    app: operative-report-web
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30007
    protocol: TCP
    name: http
  selector:
    app: operative-report-web