apiVersion: v1
kind: Service
metadata:
  name: operative-report-web-service
  namespace: operative-report
  labels:
    app: operative-report-web
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    protocol: TCP
    name: http
  selector:
    app: operative-report-web