apiVersion: apps/v1
kind: Deployment
metadata:
  name: operative-report-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operative-report-api
  template:
    metadata:
      labels:
        app: operative-report-api
    spec:
      containers:
      - name: k8stest
        image: operativereportapi:0.1
        ports:
        - containerPort: 5189
      imagePullSecrets:
        - name: regcred