apiVersion: v1
kind: Service
metadata:
  name: operative-report-api-service
  labels:
    app: operative-report-api
    kubernetes.io/service-name: operative-report-api-service
spec:
  type: NodePort
  ports:
  - port: 5189
    targetPort: 5189
    nodePort: 30189
    protocol: TCP
    name: http
  selector:
    app: operative-report-api