apiVersion: v1
kind: Service
metadata:
  name: operative-report-api-service
  namespace: operative-report
  labels:
    app: operative-report-api
    kubernetes.io/service-name: operative-report-api-service
spec:
  type: LoadBalancer
  ports:
  - port: 5189
    protocol: TCP
    name: http
  selector:
    app: operative-report-api