apiVersion: apps/v1
kind: Deployment
metadata:
  name: operative-report-api
  namespace: operative-report
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operative-report-api
  template:
    metadata:
      labels:
        app: operative-report-api
    spec:
      containers:
      - name: operative-report-api
        image: ghcr.io/ckriutz/operative-report:api-latest
        ports:
        - containerPort: 5189