name: Build and deploy the dotnet core API in a Docker image, and push to github registry.

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
    AZURE_WEBAPP_PACKAGE_PATH: '.'                  # set this to the path to your web app project, defaults to the repository root
    DOTNET_VERSION: '7'                             # set this to the .NET Core version to use

on:
    push:
        branches: [ "main" ]

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./Api
        permissions:
            contents: read
            packages: write
        steps:
        - name: Setup QEMU
          uses: docker/setup-qemu-action@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Log into registry
          uses: docker/login-action@v2.2.0
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
          with:
              images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v4.1.1
          with:
            context: "{{defaultContext}}:Api"
            push: true
            tags: operative-report-api:latest
            labels: ${{ steps.meta.outputs.tags }}