apiVersion: apps/v1
kind: Deployment
metadata:
  name: operative-report-web
  namespace: operative-report
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operative-report-web
  template:
    metadata:
      labels:
        app: operative-report-web
    spec:
      containers:
      - name: operative-report-web
        image: ghcr.io/ckriutz/operative-report:web-react-latest
        imagePullPolicy: Always
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: operative-report-config
              key: api-url
        ports:
        - containerPort: 3000